
[font]
size = 6

  [font.offset]
  x = 0
  y = 3

  [font.normal]
  family = "Adwaita Mono"
  style = "Regular"
  
  [font.bold]
  family = "Adwaita Mono"
  style = "Bold"

  [font.italic]
  family = "Adwaita Mono"
  style = "Italic"

  [font.bold_italic]
  family = "Adwaita Mono"
  style = "Bold Italic"

[window.padding]
x = 10
y = 10

[terminal]
shell = "zsh"

[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]
